# Generated by Django 3.2.5 on 2021-07-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bid',
            new_name='start_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='auction',
            name='on_list',
            field=models.BooleanField(default=True),
        ),
    ]
