# Generated by Django 3.2.5 on 2021-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auction',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
